[[redirects]]
  from = "/apps-application1/*"
  to = "https://vocal-starlight-984587.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/apps-portal/*"
  to = "https://unrivaled-cupcake-c89aeb.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true